import React from 'react'
import Pixel from './Pixel'

const App = () => {
  return (
    <div>
      {/* <div>React development has begun!</div> */}
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
    </div>
  )
}

export default App
